### ISSUE TITLE
A problem with Select and its selectedKey and function old()

### ISSUE THREAD

**Issue by joserick** [rawilk/laravel-form-components#11]
Hello, I used the v2 and v3 of laravel-form-components in different projects.

The problem is that the array of options that I gave to "x-select" has the keys numeric (int) and when comparing it with the value returned by the old() function that returns the numeric value as a string, these are not match by the triple equal "==="

https://github.com/rawilk/laravel-form-components/blob/6e9a9aa03bf787234301c47e40ac254917acf59d/src/Components/Inputs/Select.php#L56

https://github.com/rawilk/laravel-form-components/blob/6e9a9aa03bf787234301c47e40ac254917acf59d/src/Components/Inputs/Select.php#L61

**Comment by rawilk** [comment]
Thanks for pointing that out. I've released version `3.0.6`, which doesn't use the strict comparison anymore to determine if the option is selected.

**Comment by xorock** [comment]
I see a small problem here. Very often in the search form there are 3 fields for the select element e.g.: null => All, 0 => No, 1 => Yes. These fields map directly to the database, to some boolean type. Unfortunately, in php 

```php
var_dump(0 == null); // true
```
The loose comparison results in two options being checked incorrectly

```html
<select class="form-text form-select" name="filterx" id="filterx">
                    <option value="" selected="">
        All
    </option>
                    <option value="0" selected="">
        No
    </option>
                    <option value="1">
        Yes
    </option>
    </select>
```

The Laravel Collective library takes additional things into account here: https://github.com/LaravelCollective/html/blob/6.x/src/FormBuilder.php#L1299

Maybe You can also consider this fix here?

**Comment by rawilk** [comment]
I don't think that should be an issue with v8 of this package, but I'd keep an eye on it. If it becomes an issue for you, feel free to raise an issue on it.
