### ISSUE TITLE
Error to added form-components scss

### ISSUE THREAD

**Issue by joserick** [rawilk/laravel-form-components#12]
### Description
Hello,

Could you give some suggestion as to why the following error happens?:

![imagen](https://user-images.githubusercontent.com/15143699/109207893-42c1bb80-776f-11eb-83be-bbc73337941c.png)

### Steps to reproduce
**app.scss**
```scss
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
@import "../../vendor/rawilk/laravel-form-components/resources/sass/form-components";
```
**tailwind.config.js**
https://randallwilk.dev/docs/laravel-form-components/v2/upgrade#upgrading-from-v1-to-v2

**webpack.mix.js**
```js
mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css/', {}, [
        require('postcss-import'),
        require('tailwindcss'),
        require('autoprefixer'),
    ]);
```

**Context**
- Package version: [e.g. 2.0.2]
- Laravel version: [e.g. 8.27.0]

**Comment by rawilk** [comment]
This is because you do not have the `white` color configured for tailwind. You just need to ensure you have all the colors configured that the package's stylesheets are referencing.

As a note, I do plan on actually getting rid of the stylesheets in a future version and just adding each of the styles directly to the elements themselves instead of using custom classes to style them, but for now you will just need to make sure you have tailwind configured correctly.

**Comment by joserick** [comment]
Ah I understood!

Thanks to your comment I have noticed the error:
In **tailwind.config.js** https://randallwilk.dev/docs/laravel-form-components/v2/upgrade#upgrading-from-v1-to-v2
I am adding the color "blue-gray" like the example configuration but at the same time I am overwriting the all the colors with "blue-gray":
```js
const colors = require('tailwindcss/colors');
module.exports = {
    // ...
    theme: {
        colors: {
            "blue-gray": colors.blueGray,
        },
    // ...
```
I have to add "blue-gray" but in "extend" so as not to overwrite but if add:
```js
const colors = require('tailwindcss/colors');
module.exports = {
    // ...
    theme: {
        extend: {
            colors: {
                "blue-gray": colors.blueGray,
                primary: {
                    50: colors.blue["50"],
                    //...
```
And in this way it found the "bg-white"; Please could you update this in the documentation so that a human in the future does not have this problem.

Thanks!
