### ISSUE TITLE
How to deal with array values?

### ISSUE THREAD

**Issue by mikewink** [rawilk/laravel-form-components#23]
Hello Randall,

first of all thank you very much for your package. I started using it today and it's a pleasure to work with.

I ran into an issue with array values in regular (number) inputs. My data structure is simply like this `measurements[torso][t1]`. When I don't enter any value into the required field I get a proper error message back. But in the case of the old value being needed to fill the value I get nothing back. The field value is null. 

```blade
<x-form-group label="1"
              name="measurements[torso][t1]"
              :border="false">
    <x-input type="number"
             min="0"
             max="1000"
             step=".1"
             name="measurements[torso][t1]"/>
</x-form-group>
```

Before I used the package I handled the form building manually and the fields worked properly. 

```blade
<div class="col-span-6 sm:col-span-4">
    <x-jet-label for="t1" value="1"/>
    <x-jet-input id="t1"
                 name="measurements[torso][t1]"
                 type="number"
                 value="{{ old('measurements.torso.t1') }}"
                 class="mt-1 block"/>
    <x-jet-input-error for="measurements.torso.t1" class="mt-2"/>
</div>
```

I guess the reason is that I don't save the value straight into a table field? Instead I use the measurements and put them into a single table field. There are 50 values in total in that array when it's saved.

Or is it that the array is not correctly deconstructed for the old value? I see in the `Input.php` class that you json_encode the value when it is an array. As you can see I used `measurements.torso.t1` to get back my old value from the array. When and where is the json_decode(ed)?

```php
if (is_array($this->value)) {
    $this->value = json_encode($this->value);
}
```

Any help would be appreciated! Thank you very much.

Best regards

Mike

**Comment by rawilk** [comment]
Glad to hear you like the package!

Unfortunately I'm not really sure of a good way to solve the issue you've brought up. I normally don't process form submissions this way as I use Livewire instead to handle them, so I don't need to worry about data structures like this. I would recommend just manually setting the value on the input like you were before with `value="{{ old('measurements.torso.t1') }}"` as a workaround for now.

You're welcome to submit a PR if you find a solution for this too if you choose to.

**Comment by mikewink** [comment]
I did not find an immediate solution for this problem, so I went with passing the value the "old" way, into the component. It works well. I think we can close this issue. 

I'll give Livewire form handling a try and see if it mitigates the problem. 👍🏼
