### ISSUE TITLE
How to conditionally set readonly or disabled attributes?

### ISSUE THREAD

**Issue by mikewink** [rawilk/laravel-form-components#26]
Hello Randall,

How would you set conditional attributes like `readonly`or `disabled` on the input component for example?

```blade
<x-input name="order_id"
    @if ($order->order_id > 10000) ?? readonly @endif
    {{ ($order->order_id > 10000) ?? 'disabled' }}
    :value="old('order_id', $order->order_id ?? '')"/>
```

Either way does not work and results in the disappearing of the input. Do I need to extend the class for both of the attributes or how would I do this? 🤔

Best regards

Mike

**Comment by rawilk** [comment]
You can do it like this:

```html
<x-input 
    name="order_id" 
    :disabled="$order->order_id > 10000"
    :value="old('order_id', $order->order_id ?? '')"
/>
```

I believe it should work the same if you want to use `readonly` instead.

**Comment by mikewink** [comment]
Works, thank you. Learning the ropes step by step. 😅
