### ISSUE TITLE
blade-ui-kit/blade-heroicons should be moved to require instead of require dev

### ISSUE THREAD

**Issue by cdbessig** [rawilk/laravel-form-components#27]
### Description

Not a composer expert, but I think blade-ui-kit/blade-heroicons should be moved to require instead of require dev.  This is because someone who has installed your package may use the x-custom-select component which then requires icons from this package.  

### Steps to reproduce

Setup a new project, set up a custom select

```
<x-custom-select wire:model="account"
                                     :options="$accounts"
                                     value-field="id"
                                     text-field="account"
                    />
```
Watch the error appear:

```
Unable to locate a class or view for component [heroicon-s-check]. (View: .../vendor/rawilk/laravel-form-components/resources/views/partials/custom-select-option.blade.php)


**Context**
- Package version: [e.g. 1.0.0]
4.0.8
- Laravel version: [e.g. 7.0.0]
8

**Comment by rawilk** [comment]
Valid point, however the package allows you to override those icons globally in the config, or you can do it every time you render the component via props. Overriding those icons would prevent those errors from happening.
