### ISSUE TITLE
Documentation link broken 

### ISSUE THREAD

**Issue by Micaso** [rawilk/laravel-form-components#31]
### Description
First of all, thank you for the great package. 
Back then when I first installed this package, the documentation site worked. 
But currently am not able to load your documentation site anymore

### Steps to reproduce
try open https://randallwilk.dev

**Context**
not important

Thank you

**Comment by rawilk** [comment]
I've been able to load the site just fine on my end. You may have been trying to load when I was doing some maintenance or something.

Also, if there is ever anything wrong with that site itself, please open an issue on the https://github.com/rawilk/randallwilk.dev repo as it's not directly related to this package.

**Comment by Micaso** [comment]
Thank you for looking into this. I am now also be able to load the page. 
Sorry for opening in the wrong repo. I will be more carful in the feature if anything comes up again.
