### ISSUE TITLE
Use key => value syntax for select components?

### ISSUE THREAD

**Issue by luilliarcec** [rawilk/laravel-form-components#33]
You could use this syntax for the options of the select components. It works a bit cleaner even when doing `pluck()->toArray` on some collection.

**Comment by rawilk** [comment]
could you provide an example?

**Comment by luilliarcec** [comment]
Sorry, I was talking about the custom select, but reviewing the code I understood why it uses "value" and "text" keys. 

On the other hand, it might be a better idea to create an x-for to loop through the values ​​and create an input for each value with array name instead of passing a single input with the data in json, for when Livewire is not used.  

I suppose but I think it would be to analyze it.  

Excellent package, I enjoy using it.
