### ISSUE TITLE
Date picker strange behaviour 

### ISSUE THREAD

**Issue by beneyraheem** [rawilk/laravel-form-components#37]
```<x-date-picker name="date"   />```

this always gives null value  in livewire. Also UI breaks when used wire:model="date"

**Comment by beneyraheem** [comment]
```
@if ($value && !$attributes->hasStartsWith('wire:model'))
    value: '{{ $value }}',
@elseif ($attributes->hasStartsWith('wire:model'))
    value: @entangle($attributes->wire('model')),
@else
    value: null,
    @endif
```

why it makes value:null at the end? its the problem here

**Comment by beneyraheem** [comment]
also
``` :value="now()->format('Y-m-d')" ```

this doesnt work with livewire

**Comment by huuloc4193** [comment]
Hello, I had the same problem.
An error message while using wire:more="date"

`Livewire Entangle Error: Livewire property 'date' cannot be found`

Pls fix.

thank you so much

**Comment by rawilk** [comment]
You need to use `wire:model` in a livewire component.

> Also UI breaks when used wire:model="date"

That's pretty vague and I don't know how to help you with that. I've never had an issue with it, so it's probably something in your codebase that's breaking it.

> also
> `:value="now()->format('Y-m-d')"
>
> this doesn't work with livewire

The component is designed to not render a "value" on the input if it detects you are using `wire:model`. I have no plans on changing this, but feel free to fork and maintain your own version for your own needs.

**Comment by rawilk** [comment]
@huuloc4193 The error you are receiving is not related to this package. You don't have the `date` property defined on your livewire component, which is why you're getting that error.

**Comment by huuloc4193** [comment]
> @huuloc4193 The error you are receiving is not related to this package. You don't have the `date` property defined on your livewire component, which is why you're getting that error.

First of all, thank you for your reply, and sorry for my post was incorrect before.

My code in blade below:

`<x-date-picker wire:model.lazy="date" name="date" id="date" class="form-control" />  `

and error message

`Livewire Entangle Error: Livewire property 'date' cannot be found`

**Comment by rawilk** [comment]
You need to define a `public $date` property on your livewire component.

Again, this is not related to this package.
