### ISSUE TITLE
Custom select breaks when value is get from old and is an integer

### ISSUE THREAD

**Issue by luilliarcec** [rawilk/laravel-form-components#40]
### Laravel Form Components Version

v6.0.0

### Laravel Version

v8.63.0

### Alpine Version

v3.4.2

### Bug description

When using the component outside of Livewire, the component breaks if the selected value is an integer but only when it is obtained from old, this happens because the value returned by old is transformed to a string. For example select Apple with key 1 when old returns it to me is "1".

![image](https://user-images.githubusercontent.com/27895611/136462991-a9604316-75d6-4290-8c6a-5787fbbc947c.png)

![image](https://user-images.githubusercontent.com/27895611/136463035-499394ab-c3fa-4edd-933c-580f40f86cdc.png)

As I mention. this happens after submitting and receiving the value of old.

I investigated the source code and the selectedKey property returns the correct array, however, this seems to be one more JS error due to the triple comparison that exists in the following lines of code.

[custom-select.js#L185](https://github.com/luilliarcec/laravel-form-components/blob/d1f031731029d41fd8cf68ad8d754043b99b16a4/resources/js/components/custom-select.js#L185)

[custom-select.js#L187](https://github.com/luilliarcec/laravel-form-components/blob/d1f031731029d41fd8cf68ad8d754043b99b16a4/resources/js/components/custom-select.js#L187)

However, it is a somewhat vague assessment, I have not tested it to be true, if changing said comparison solves the problem.

### Steps to reproduce

```php
Model::create([
  'id' => 1,
  'name' => 'Laravel'
]);

$data = Model::get(['id', 'name']);
```

```blade
<x-custom-select
    :options="$data"
    value-field="id"
    text-field="name"
    name="model_name_input"
    filterable
    multiple
    optional
/>
```

**Comment by luilliarcec** [comment]
Maybe I can assure that the problem is the triple JS comparison ... I tried casting my Id to string and it really worked.

![image](https://user-images.githubusercontent.com/27895611/136464736-0ff8c419-a799-41fb-905f-ce37e8d6ef44.png)

![image](https://user-images.githubusercontent.com/27895611/136465030-a8895413-c040-4a78-b8be-218a26bc833a.png)

![image](https://user-images.githubusercontent.com/27895611/136465072-e7e06d91-2352-40cc-80a3-907392cadb26.png)

**Comment by rawilk** [comment]
I'll be revamping the custom select component in a major release I'm working on right now, so hopefully this kind of issue will be addressed when I get the chance to work on it.
