### ISSUE TITLE
[Feature Request]: Datepicker working with livewire

### ISSUE THREAD

**Issue by magarrent** [rawilk/laravel-form-components#63]
### Feature Description

Use datepicker (flatpickr) with livewire (wire:model)

**Comment by rawilk** [comment]
Please read the docs. This is already possible.

**Comment by rawilk** [comment]
It works just like the other inputs do. I'm not sure what you mean by "doesn't work", but if you have your livewire component set up correctly, a `wire:model` will work for it.

```php
class MyComponent extends Component
{
    public $myDate;
}
```

`<x-date-picker wire:model="myDate" />`
