### ISSUE TITLE
How to edit images on FilePond component

### ISSUE THREAD

**Issue by magarrent** [rawilk/laravel-form-components#65]
### Feature Description

Hey there! I'm using Filepond component with Livewire. The question is how to edit those images once you uploaded it?

Like editing a blog post with an image already set. Is that currently possible?

**Comment by rawilk** [comment]
Sorry for the late reply. I believe this is outside of the scope of this package and component. If I understand you correctly, you would need show the current image on an edit page with a way for the user to either remove the image and/or click a button or something to upload a new image.
