### ISSUE TITLE
Can't install in Laravel 10

### ISSUE THREAD

**Issue by albertobenavides** [rawilk/laravel-form-components#77]
### Laravel Form Components Version

lastest

### Laravel Version

10

### Alpine Version

3

### Bug description

Error after trying to install from composer.

### Steps to reproduce

Run
```
composer require rawilk/laravel-form-components
```

### Relevant log output

```shell
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires rawilk/laravel-form-components ^7.1 -> satisfiable by rawilk/laravel-form-components[v7.1.0, ..., v7.1.6].
    - rawilk/laravel-form-components[v7.1.0, ..., v7.1.6] require illuminate/filesystem ^8.70|^9.0 -> found illuminate/filesystem[v8.70.0, ..., v8.83.27, v9.0.0, ..., v9.52.0] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require rawilk/laravel-form-components:*" to figure out if any version is installable, or "composer require rawilk/laravel-form-components:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by lartisan** [comment]
+1

**Comment by rawilk** [comment]
I will be releasing an update soon with Laravel 10.x compatibility, as well as a new major version upcoming soon as well too. The new major version is what is holding things up right now, but I plan on having it done this week yet.

**Comment by albertobenavides** [comment]
Nice. In the meantime I had a workarround going. I will be checking for updates :)

**Comment by rawilk** [comment]
I've just tagged `v7.1.7` with composer updated to support it. I'm still working on v8 but I wanted to at least patch v7 in the mean time.

**Comment by rawilk** [comment]
Closing this issue as it should be resolved, especially with v8 being released now.
