### ISSUE TITLE
Alpine.js headless components conflict

### ISSUE THREAD

**Issue by booni3** [rawilk/laravel-form-components#79]
### Laravel Form Components Version

7.1.6

### Laravel Version

9.50.1

### Alpine Version

3.10.5

### Bug description

$disclosure is a new magic method which ships with the new Alpine beta and is used in the new headless alpine components.

Including the `@fcScripts` causes the error, while, `@fcJavaScript` works OK.

Does fcScripts also load AlpineJs?

**Comment by rawilk** [comment]
`@fcScripts` does also load Alpine from a CDN. I'm working on v8 of this package right now, and I'm thinking of just getting rid of that directive all together.

**Comment by rawilk** [comment]
v8 of the package should work fine with those components. Feel free to re-open this issue if you're still having compatibility issues.
